name: GioSDAs-Economy
version: '${project.version}'
main: io.github.giosda.giosdaeconomy.Economy
api-version: 1.18
authors: [ GioSDA ]
description: GioSDA's economy plugin

commands:
  balance:
    description: Get player balance.
    aliases: [balance, bal]
    usage: "Usage: /<command> [player]"
    default: true
  pay:
    description: Pay a player money.
    aliases: [pay, give]
    usage: "Usage: /<command> [player] [amount]"
    default: true
  auction:
    description: Check the auction house.
    aliases: [auction, ah, auctionhouse]
    usage: "Usage: /<command>"
    default: true
  debug:
    description: debug.
    default: op